### ISSUE TITLE
Locks up on boot after installing limelight through tripi menu

### ISSUE THREAD

**Issue by sticklerthe1st** [arka9ine/TriPi-Updater#6]
Hello, I ran the tri-pi update and noticed it had a limelight install so I tried that. On reboot it froze on a white screen after displaying the emulation station logo. I reinstalled from a backed up image and installed limelight through the retropi menu and it worked without locking up. Tried to install through the menu again and was met with same result.

**Comment by arka9ine** [comment]
Had you made any previous modifications to your system before taking the latest update, or did you update from a fresh image?

**Comment by sticklerthe1st** [comment]
Nothing changed besides roms being on my backup image, as far as I know. I will use a default image and try with a different sd card to make sure.

**Comment by arka9ine** [comment]
Yeah make a fresh install and run the updater, then try again.

I just updated things for version 4.6 so let me know if you run into any other issues along the way. Posting them as a comment here is fine.

**Comment by sticklerthe1st** [comment]
Sorry for the late reply, I recently updated everything but limelight and compiled moonlight and it works wonderfully. I noticed a few changes so the updates for the rest of the system went correctly. I just found another sdcard so I will try that today to make sure it isn't user error on my end today and let you know.

There is one more thing I had problems with, the global config menu not saving via menu. For example, I change users from 5 to 2 but on exit/reboot it defaults back to 5, or changing gl to sdl and so on.  I gotta edit manually but no big deal. I am probably doing something wrong but I think it was worth to note.

The second problem is I cannot get the nds emulator to install/compile no matter what. Is this a known bug or is there a work around? I installed the binary via apt-get but it is not compatible with the menu like the other emus. I like to have the menu to change things easier like most the other emulators.

Great work on tripi by the way, I started with retropie but it was difficult to get the xbox controller to work with kodi. I use my phone as a remote now so I guess the point is moot but still, great work. I plan on sticking with tripi.

**Comment by arka9ine** [comment]
I'm glad to hear that things are working for you now!
As far as the retroarch config, you will need to stick to manual config for now. I am aware of that issue, but have not found a solution to it just yet. Can't tell if it's a TriPi-specific issue, or an issue with retroarch that only conflicts with something TriPi-related.

As far as the NDS emu, I have not attempted to use it at all, so I can't provide any further information on it. If it isn't backed by retroarch, I'm not going to be focusing on it much, either unless it becomes high enough demand for TriPi in particular.

Closing as original issue is resolved. Open another issue for other subjects if you have any more questions on those matters.
